version: '3'

services:
  gerrit:
    image: docker.io/gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "80:8080"
    depends_on:
      - ldap
    volumes:
      - ./external/gerrit/etc:/var/gerrit/etc
      - ./external/gerrit/git:/var/gerrit/git
      - ./external/gerrit/db:/var/gerrit/db
      - ./external/gerrit/index:/var/gerrit/index
      - ./external/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://localhost
    # command: init

  ldap:
    image: docker.io/osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - ./external/gerrit/ldap/var:/var/lib/ldap
      - ./external/gerrit/ldap/etc:/etc/ldap/slapd.d

  ldap-admin:
    image: docker.io/osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

networks:
  default:
    name: growi-docker-compose_default
    external: true
